"""Clear cached interview questions from the Qdrant vector DB.

Why this exists
---------------
Generated questions are cached in Qdrant (collection ``interview_questions`` by
default) so future searches are fast. There is no quality gate before caching,
so low-quality questions generated by an older prompt persist and keep getting
served — even after the generation prompt is fixed. This script purges that
cache so fresh, clean questions are generated on the next search.

The cache is fully regenerable: clearing it loses nothing permanent.

Usage (from the repo root, with your .env configured)::

    # Preview what would be removed (no changes):
    python scripts/clear_question_cache.py --dry-run

    # Delete ONLY formulaic "X uses Y" / "role of Y in X" questions:
    python scripts/clear_question_cache.py --formulaic

    # Delete questions whose text contains a substring (case-insensitive):
    python scripts/clear_question_cache.py --contains "Agentic AI"

    # Nuke the whole cache (recreate the collection empty):
    python scripts/clear_question_cache.py --all
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Allow running as `python scripts/clear_question_cache.py` from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.config import settings  # noqa: E402

try:
    from qdrant_client import QdrantClient
    from qdrant_client.models import Distance, VectorParams
except ModuleNotFoundError:
    print("qdrant_client is not installed. Install Interview Intelligence deps first.")
    sys.exit(1)


# Formulaic shapes the old skill-polluted generation produced, e.g.
#   "Explain how Agentic AI uses Python for ..."
#   "Explain the role of HTML in Agentic AI applications"
#   "How does JavaScript enable ... in Agentic AI"
# These match the STRUCTURE ("<subject> uses <thing> for/to", "role of <thing> in
# <subject>", "how does <thing> enable/use ...") rather than a hardcoded skill
# list, so they generalise to any technology the resume happened to contain.
#
# The patterns live in app.utils.question_quality because the same definition
# gates cache WRITES in _store_in_vector_db. Evicting a shape here without also
# blocking it there would just let it be regenerated on the next search.
from app.utils.question_quality import is_formulaic as _is_formulaic  # noqa: E402


def _connect() -> QdrantClient:
    url = getattr(settings, "qdrant_url", None)
    if url:
        print(f"Connecting to Qdrant server: {url}")
        return QdrantClient(url=url, api_key=getattr(settings, "qdrant_api_key", None))

    # Local-path mode: use the SAME path the app uses, not a guess. The local
    # Qdrant is single-process — stop the dev server first or this will fail to
    # acquire the lock.
    from app.services.interview.interview_intelligence_service import VECTOR_DB_PATH

    local_path = str(VECTOR_DB_PATH)
    print(f"Connecting to local Qdrant at: {local_path}")
    print("NOTE: local Qdrant is single-process - stop the dev server first if this hangs/errors.")
    return QdrantClient(path=local_path)




def main() -> int:
    parser = argparse.ArgumentParser(description="Clear cached interview questions from Qdrant.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--all", action="store_true", help="Delete ALL cached questions (recreate empty collection).")
    group.add_argument("--formulaic", action="store_true", help="Delete only formulaic 'X uses Y' style questions.")
    group.add_argument("--contains", metavar="TEXT", help="Delete questions whose text contains TEXT (case-insensitive).")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be deleted without deleting.")
    args = parser.parse_args()

    collection = getattr(settings, "qdrant_collection_name", "interview_questions")
    client = _connect()

    existing = {c.name for c in client.get_collections().collections}
    if collection not in existing:
        print(f"Collection '{collection}' does not exist - nothing to clear.")
        return 0

    total = client.count(collection_name=collection, exact=True).count
    print(f"Collection '{collection}' has {total} cached questions.")

    # --all: drop and recreate the collection empty.
    if args.all:
        if args.dry_run:
            print(f"[dry-run] Would delete and recreate collection '{collection}' (removing all {total}).")
            return 0
        client.delete_collection(collection_name=collection)
        client.create_collection(
            collection_name=collection,
            vectors_config=VectorParams(size=384, distance=Distance.COSINE),
        )
        print(f"Done: cleared all {total} questions; recreated empty collection '{collection}'.")
        return 0

    # Targeted: scroll the whole collection and select matching point ids.
    contains = (args.contains or "").lower().strip()
    to_delete: list = []
    scanned = 0
    offset = None
    while True:
        points, offset = client.scroll(
            collection_name=collection,
            limit=256,
            offset=offset,
            with_payload=True,
            with_vectors=False,
        )
        for p in points:
            scanned += 1
            question = str((p.payload or {}).get("question", ""))
            match = _is_formulaic(question) if args.formulaic else (contains in question.lower())
            if match:
                to_delete.append(p.id)
        if offset is None:
            break

    print(f"Scanned {scanned} questions; {len(to_delete)} match the selection.")
    if args.dry_run:
        for pid in to_delete[:20]:
            print(f"  [dry-run] would delete id={pid}")
        if len(to_delete) > 20:
            print(f"  ... and {len(to_delete) - 20} more")
        return 0

    if not to_delete:
        print("Nothing to delete.")
        return 0

    client.delete(collection_name=collection, points_selector=to_delete)
    print(f"Done: deleted {len(to_delete)} matching questions from '{collection}'.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
